### ISSUE TITLE
Resistance tests

### ISSUE THREAD

**Issue by sagi-brudni** [naomikorem/MarketSystem#146]
- [x] check bad cases when using extrnal services
- [x] check bad cases when using database
- [x] check that the system is not loaded if something went wrong with initialization

**use another configuration file (connect sub database and external services)**

implementation emphasis 4

**Comment by sapirani** [comment]
https://github.com/naomikorem/MarketSystem/blob/milestone4/ServerFiles/src/main/java/ResistanceTests/HttpClientPostTest.java#L78-L82
