### ISSUE TITLE
2.a. Functional requirements 

### ISSUE THREAD

**Issue by Noa-Izsak** [naomikorem/MarketSystem#4]
system: 

- [x] 1
- [x] 3
- [x] 4

**Comment by sapirani** [comment]
for requirement 1 in system:

https://github.com/naomikorem/MarketSystem/blob/a39b24b2ec1983db110c09f352ac753e77e5c0c7/src/main/java/DomainLayer/SystemManagement/MarketManagementFacade.java#L31-L47

for requirement 3 in system: 

https://github.com/naomikorem/MarketSystem/blob/a39b24b2ec1983db110c09f352ac753e77e5c0c7/src/main/java/DomainLayer/SystemManagement/ExternalServices/SupplyServices/SupplyProxy.java#L32-L41

for requirement 4 in system: 

https://github.com/naomikorem/MarketSystem/blob/a39b24b2ec1983db110c09f352ac753e77e5c0c7/src/main/java/DomainLayer/SystemManagement/ExternalServices/PurchaseServices/PurchaseProxy.java#L27-L38

using requirements 3 and 4:

https://github.com/naomikorem/MarketSystem/blob/a39b24b2ec1983db110c09f352ac753e77e5c0c7/src/main/java/DomainLayer/SystemManagement/PurchaseProcess.java#L37-L67
